<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AdministrarMetodosPago.aspx.cs" Inherits="VVuelos.AdministrarMetodosPago" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

     <asp:Button ID="btn_guardar" runat="server" OnClick="btn_guardar_Click" Text="Guardar" />

    <asp:Button ID="btn_lista" runat="server" OnClick="btn_lista_Click" Text="Lista" />

     <asp:Label ID="lbl_usuario" runat="server" ForeColor="Red"></asp:Label>

           <asp:GridView ID="GV_Tarjetas" runat="server" AllowPaging="True" AutoGenerateColumns="False" DataKeyNames="id" PageSize="5" OnPageIndexChanging="GV_Tarjetas_PageIndexChanging" AutoGenerateDeleteButton="False" EditRowStyle-Wrap="False">
        <Columns>
            <asp:BoundField DataField="Usuario" HeaderText="Usuario" />
            <asp:BoundField DataField="Numero_Tarjeta" HeaderText="Número de Tarjeta" />
        </Columns>
    </asp:GridView>

    </asp:Content>

