<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true"  CodeBehind="Bitacora.aspx.cs" Inherits="VVuelos.Bitacora" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
     <asp:Label ID="Label1" runat="server" ForeColor="Red"></asp:Label>
       <asp:GridView ID="GV_Bitacora" runat="server" AllowPaging="True" AutoGenerateColumns="False" DataKeyNames="id" PageSize="5" OnPageIndexChanging="GV_Bitacora_PageIndexChanging" AutoGenerateDeleteButton="False" EditRowStyle-Wrap="False">
        <Columns>
            <asp:BoundField DataField="usuario" HeaderText="Usuario" />
             <asp:BoundField DataField="codigo_registro" HeaderText="Código" />
            <asp:BoundField DataField="descripcion" HeaderText="Descripción" />
            <asp:BoundField DataField="fecha_hora" HeaderText="Fecha y Hora" />
            <asp:BoundField DataField="tipo" HeaderText="Tipo" />
            <asp:HyperLinkField DataNavigateUrlFields="id" DataNavigateUrlFormatString="AdministrarPaises?cod={0}" Text="Editar" />
        </Columns>
    </asp:GridView>
    
    <asp:Label ID="Label3" runat="server" ForeColor="Red"></asp:Label>
    <asp:Button ID="btn_nuevo" runat="server" Text="Nuevo" OnClick="btn_nuevo_Click" />

 

</asp:Content>

