//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VVuelos.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/devolverTarjeta", ReplyAction="http://tempuri.org/IService/devolverTarjetaResponse")]
        string devolverTarjeta(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/devolverTarjeta", ReplyAction="http://tempuri.org/IService/devolverTarjetaResponse")]
        System.Threading.Tasks.Task<string> devolverTarjetaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/devolverEasyPay", ReplyAction="http://tempuri.org/IService/devolverEasyPayResponse")]
        string devolverEasyPay(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/devolverEasyPay", ReplyAction="http://tempuri.org/IService/devolverEasyPayResponse")]
        System.Threading.Tasks.Task<string> devolverEasyPayAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/cargarTarjeta", ReplyAction="http://tempuri.org/IService/cargarTarjetaResponse")]
        System.Data.DataSet cargarTarjeta(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/cargarTarjeta", ReplyAction="http://tempuri.org/IService/cargarTarjetaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> cargarTarjetaAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/cargarEasyPay", ReplyAction="http://tempuri.org/IService/cargarEasyPayResponse")]
        System.Data.DataSet cargarEasyPay(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/cargarEasyPay", ReplyAction="http://tempuri.org/IService/cargarEasyPayResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> cargarEasyPayAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insertarTarjeta", ReplyAction="http://tempuri.org/IService/insertarTarjetaResponse")]
        void insertarTarjeta(string usuario, int numero, int mes_expiracion, int año_expiracion, int cvv, decimal monto, string emisor, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insertarTarjeta", ReplyAction="http://tempuri.org/IService/insertarTarjetaResponse")]
        System.Threading.Tasks.Task insertarTarjetaAsync(string usuario, int numero, int mes_expiracion, int año_expiracion, int cvv, decimal monto, string emisor, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insertarEasyPay", ReplyAction="http://tempuri.org/IService/insertarEasyPayResponse")]
        void insertarEasyPay(string usuario, int numero, int codigo_seguridad, string contraseña, decimal monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insertarEasyPay", ReplyAction="http://tempuri.org/IService/insertarEasyPayResponse")]
        System.Threading.Tasks.Task insertarEasyPayAsync(string usuario, int numero, int codigo_seguridad, string contraseña, decimal monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/modificarTarjeta", ReplyAction="http://tempuri.org/IService/modificarTarjetaResponse")]
        void modificarTarjeta(int ID, string usuario, int numero, int mes_expiracion, int año_expiracion, int cvv, decimal monto, string emisor, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/modificarTarjeta", ReplyAction="http://tempuri.org/IService/modificarTarjetaResponse")]
        System.Threading.Tasks.Task modificarTarjetaAsync(int ID, string usuario, int numero, int mes_expiracion, int año_expiracion, int cvv, decimal monto, string emisor, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/modificarEasyPay", ReplyAction="http://tempuri.org/IService/modificarEasyPayResponse")]
        void modificarEasyPay(int ID, string usuario, int numero, int codigo_seguridad, string contraseña, decimal monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/modificarEasyPay", ReplyAction="http://tempuri.org/IService/modificarEasyPayResponse")]
        System.Threading.Tasks.Task modificarEasyPayAsync(int ID, string usuario, int numero, int codigo_seguridad, string contraseña, decimal monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/eliminarTarjeta", ReplyAction="http://tempuri.org/IService/eliminarTarjetaResponse")]
        void eliminarTarjeta(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/eliminarTarjeta", ReplyAction="http://tempuri.org/IService/eliminarTarjetaResponse")]
        System.Threading.Tasks.Task eliminarTarjetaAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/eliminarEasyPay", ReplyAction="http://tempuri.org/IService/eliminarEasyPayResponse")]
        void eliminarEasyPay(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/eliminarEasyPay", ReplyAction="http://tempuri.org/IService/eliminarEasyPayResponse")]
        System.Threading.Tasks.Task eliminarEasyPayAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : VVuelos.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<VVuelos.ServiceReference1.IService>, VVuelos.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string devolverTarjeta(int id) {
            return base.Channel.devolverTarjeta(id);
        }
        
        public System.Threading.Tasks.Task<string> devolverTarjetaAsync(int id) {
            return base.Channel.devolverTarjetaAsync(id);
        }
        
        public string devolverEasyPay(int id) {
            return base.Channel.devolverEasyPay(id);
        }
        
        public System.Threading.Tasks.Task<string> devolverEasyPayAsync(int id) {
            return base.Channel.devolverEasyPayAsync(id);
        }
        
        public System.Data.DataSet cargarTarjeta(string usuario) {
            return base.Channel.cargarTarjeta(usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> cargarTarjetaAsync(string usuario) {
            return base.Channel.cargarTarjetaAsync(usuario);
        }
        
        public System.Data.DataSet cargarEasyPay(string usuario) {
            return base.Channel.cargarEasyPay(usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> cargarEasyPayAsync(string usuario) {
            return base.Channel.cargarEasyPayAsync(usuario);
        }
        
        public void insertarTarjeta(string usuario, int numero, int mes_expiracion, int año_expiracion, int cvv, decimal monto, string emisor, string tipo) {
            base.Channel.insertarTarjeta(usuario, numero, mes_expiracion, año_expiracion, cvv, monto, emisor, tipo);
        }
        
        public System.Threading.Tasks.Task insertarTarjetaAsync(string usuario, int numero, int mes_expiracion, int año_expiracion, int cvv, decimal monto, string emisor, string tipo) {
            return base.Channel.insertarTarjetaAsync(usuario, numero, mes_expiracion, año_expiracion, cvv, monto, emisor, tipo);
        }
        
        public void insertarEasyPay(string usuario, int numero, int codigo_seguridad, string contraseña, decimal monto) {
            base.Channel.insertarEasyPay(usuario, numero, codigo_seguridad, contraseña, monto);
        }
        
        public System.Threading.Tasks.Task insertarEasyPayAsync(string usuario, int numero, int codigo_seguridad, string contraseña, decimal monto) {
            return base.Channel.insertarEasyPayAsync(usuario, numero, codigo_seguridad, contraseña, monto);
        }
        
        public void modificarTarjeta(int ID, string usuario, int numero, int mes_expiracion, int año_expiracion, int cvv, decimal monto, string emisor, string tipo) {
            base.Channel.modificarTarjeta(ID, usuario, numero, mes_expiracion, año_expiracion, cvv, monto, emisor, tipo);
        }
        
        public System.Threading.Tasks.Task modificarTarjetaAsync(int ID, string usuario, int numero, int mes_expiracion, int año_expiracion, int cvv, decimal monto, string emisor, string tipo) {
            return base.Channel.modificarTarjetaAsync(ID, usuario, numero, mes_expiracion, año_expiracion, cvv, monto, emisor, tipo);
        }
        
        public void modificarEasyPay(int ID, string usuario, int numero, int codigo_seguridad, string contraseña, decimal monto) {
            base.Channel.modificarEasyPay(ID, usuario, numero, codigo_seguridad, contraseña, monto);
        }
        
        public System.Threading.Tasks.Task modificarEasyPayAsync(int ID, string usuario, int numero, int codigo_seguridad, string contraseña, decimal monto) {
            return base.Channel.modificarEasyPayAsync(ID, usuario, numero, codigo_seguridad, contraseña, monto);
        }
        
        public void eliminarTarjeta(int ID) {
            base.Channel.eliminarTarjeta(ID);
        }
        
        public System.Threading.Tasks.Task eliminarTarjetaAsync(int ID) {
            return base.Channel.eliminarTarjetaAsync(ID);
        }
        
        public void eliminarEasyPay(int ID) {
            base.Channel.eliminarEasyPay(ID);
        }
        
        public System.Threading.Tasks.Task eliminarEasyPayAsync(int ID) {
            return base.Channel.eliminarEasyPayAsync(ID);
        }
    }
}
